### ISSUE TITLE
Support for CRLF

### ISSUE THREAD

**Issue by modelga** [Mitranim/gulp-html-to-js#1]
Hi, would be great to have full support for CRLF and CR line endings.

**Comment by mitranim** [comment]
Pushed https://github.com/Mitranim/gulp-html-to-js/releases/tag/0.0.2, please see if this helps.

**Comment by modelga** [comment]
I have these configuration of 

```
gulp.task('html-templates', function() {
  return gulp.src(templatesDir)
    .pipe(htmlToJs({concat: 'templates.js'}))
    .pipe(gulp.dest('.'));
});
```

And after your changes I cannot create any output. Maybe you get something wrong after updating dependencies, or any other changes made impact into this. Old version still works well.

**Comment by mitranim** [comment]
Oops sorry made a mistake while updating. Should work now.

**Comment by modelga** [comment]
Great Job! Now works correctly, whilst you was working on issue, I omit these by two things (set LF endings, and apply minifyHTML before htmlToJs)
