### ISSUE TITLE
htmlToJs({global: 'window.templates'} ) doesn't work for me.

### ISSUE THREAD

**Issue by ghost** [Mitranim/gulp-html-to-js#4]
Hello!
I'm running gulp task such as:
`var outputdir = "./Debug";
var gulp = require('gulp');
var htmlToJs = require('gulp-html-to-js');
gulp.task('inject', function() {
  return gulp.src('./FieldValueEditor.html')
    .pipe(htmlToJs({global: 'window.templates'} ))
    .pipe(gulp.dest(outputdir));
});`

Unfortunately the resulting file still contains:
`'use strict';module.exports = '<div>Hello Wordl!</div>\n<div></div>';`

**Comment by mitranim** [comment]
The `global` option also requires `concat`. Your options should look like this: `{concat: 'templates.js', global: 'window.templates'}`. The documentation doesn't make this clear, my apologies.

(Edit: updated the readme.)

**Comment by ghost** [comment]
Thanks. Now it works.
